### ISSUE TITLE
Error using horzcat

### ISSUE THREAD

**Issue by kevinx001** [ArizaWilmerUTAS/Multi-Output-GPs-Identification-SHIP#1]
Error using horzcat
The dimensions of concatenated matrices are not consistent.
Error MultiOutputGPSSI (line 39)
Input = [inputYT(:,2:end) inputUT(:,2:3)]; % assemble data for normzalization
how can I do next？

**Comment by ArizaWilmerUTAS** [comment]
I had updated the data files. Such that the number of rows match
